#!/bin/sh

echo "Running some compilation tests"

CONFIGURATIONS_TO_TEST=$(cat <<HereList
E200 filamentRunout:Disabled screen:Disabled
E200 filamentRunout:Disabled screen:Enabled
E200 filamentRunout:Enabled screen:Disabled
E200 filamentRunout:Enabled screen:Enabled
D200_Melzi endstops:NC z-probe:White printer-head:Original-V1 box-filamentRunout:Disabled
D200_Melzi endstops:NC z-probe:White printer-head:Easy-V2 box-filamentRunout:Disabled
D200_Melzi endstops:NC z-probe:White printer-head:Original-V1 box-filamentRunout:Enabled
D200_Melzi endstops:NC z-probe:White printer-head:Easy-V2 box-filamentRunout:Enabled
D200_MKS screen:Enabled wifi:None
D200_MKS screen:Disabled wifi:None
Neva version:1.0
Neva version:1.1
E350 tools:Mono-Extruder z-carriage:Dual z-probe:bl-touch zsteps:4mm
HereList
)

echo "$CONFIGURATIONS_TO_TEST" > /tmp/configurations_to_test.list 

while read config_to_test
do
	echo "Testing compilation of: ${config_to_test}"
	LinuxAddons/Dagoma/bin/apply_configuration -gcof ${config_to_test}

	if test "$?" -ne "0"
        then
                echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
                echo "Unable to apply configuration: ${config_to_test}"
                exit 1
        fi 

	
	# Compilation test
	pio run -d Marlin/ > /dev/null

	# Testing result ouput
	if test "$?" -ne "0"
	then
		echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
		echo "Compilation error for configuration: ${config_to_test}"
		exit 1
	fi 
done < /tmp/configurations_to_test.list

echo "All comilations test : SUCCESS"
