#ifndef CONFIGURATION_POST_H
#define CONFIGURATION_POST_H

#undef LANGUAGE_INCLUDE
#define LANGUAGE_INCLUDE GENERATE_LANGUAGE_INCLUDE(fr)

#undef DEFAULT_NOMINAL_FILAMENT_DIA
#define DEFAULT_NOMINAL_FILAMENT_DIA 1.75

#undef TEMP_WINDOW
#define TEMP_WINDOW 3

#undef TEMP_BED_WINDOW
#define TEMP_BED_WINDOW 3

#endif