name: CI

on:
  push:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/**'

jobs:
  firmware-compilation-checks:
    name: Firmware compilation checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Apply DE200 with all options configuration
      run: ./LinuxAddons/Dagoma/bin/apply_configuration -gcof E200 bicolor:Enabled filamentRunout:Enabled screen:French thermistance:Black trapez:Enabled xl:Enabled
    - name: Run PlatformIO for DE200 with all options
      run: platformio run --environment megaatmega2560
    - name: Apply Magis configuration
      run: ./LinuxAddons/Dagoma/bin/apply_configuration -gcof Neva version:Magis
    - name: Run PlatformIO for Magis
      run: platformio run --environment megaatmega2560
    - name: Apply DU with all options configuration
      run: ./LinuxAddons/Dagoma/bin/apply_configuration -gcof Ultimate bicolor:Enabled screen:French thermistance:Black xl:Enabled
    - name: Run PlatformIO for DU with all options
      run: platformio run --environment megaatmega2560