name: Build Sigma firmware

on: workflow_dispatch

jobs:
  firmware-compilation-checks:
    name: Firmware compilation for Sigma
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Apply selected configuration
      run: ./LinuxAddons/Dagoma/bin/apply_configuration -gcof Sigma
    - name: Run PlatformIO
      run: platformio run --environment megaatmega2560
    - name: Archive compiled firmware
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: .pio/build/megaatmega2560/firmware.hex
